{% set name = "earthkit-utils" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e1bed1bd0d889441f76dd7d747824e74fbadd06f8cdf0575968061be28c6b702


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61
    - setuptools-scm >=8
  run:
    - array-api-compat
    - pint
    - python >={{ python_min }}

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - earthkit.utils

about:
  home: https://github.com/ecmwf/earthkit-utils
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Utilities for the Earthkit ecosystem.
  dev_url: https://github.com/ecmwf/earthkit-utils

extra:
  recipe-maintainers:
    - sandorkertesz
    - iainrussell
